# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HR Informatica
author: INF Studenten
email:
  - 0964703@hr.nl
  - 0966476@hr.nl
description: >- # this means to ignore newlines until "baseurl:"
  Hogeschool Rotterdam vakken gids.
  Gemaakt door studenten, voor studenten
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hr-informatica.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: nl_NL
# twitter_username: jekyllrb
github_username: HR-Informatica

# Build settings
markdown: kramdown
theme: minima
collections_dir: vakken
collections:
  ana_foundation_of_modeling:
    name: Analyse - Foundation of modeling
    course_code: INFANL03-2 / INFANL23-2
    output: true
  ana_software_analyse_design:
    name: Analyse - Software Analyse & Design
    course_code: INFSAD01-A / INFSAD21-A
    output: true
  ana_software_quality:
    name: Analyse - Software Quality
    course_code: INFSWQ01-A / INFSWQ21-A
    output: true
  dev_algorithms:
    name: Development - Algorithms
    course_code: INFALR01-D / INFALR21-D
    output: true
  dev_functional_programming:
    name: Development - Functional Programming
    course_code: INFFPR01-D / INFFPR21-D
    output: true
# plugins:
  # - jekyll-feed
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
