# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HR Informatica
author: INF Studenten
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hogeschool Rotterdam vakken gids.
  Gemaakt door studenten, voor studenten
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hr-informatica.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: HR-Informatica

# Build settings
markdown: kramdown
theme: minima
# plugins:
  # - jekyll-feed

minima:
  skin: dark

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
